config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
	require 'sidekiq/web'
	Sidekiq::Web.use Rack::Auth::Basic do |username, password|
		ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(Rails.application.secrets.sedekiq_username)) &
		ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(Rails.application.secrets.sedekiq_password))
	end
	mount Sidekiq::Web, at: '/sidekiq'

	use_doorkeeper
	devise_for :users, ActiveAdmin::Devise.config.merge(
		skip: [:confirmations, :registrations, :unlocks]
	)
	ActiveAdmin.routes(self)

	root 'home#index'

	post 'results' => 'home#results'

	scope module: 'api' do
		scope '1', module: 'v1' do
			resources :users do
				patch 'update_device_token' => 'devices#update_device_token'
				devise_scope :user do
					get 'forgot_password' => 'passwords#forgot_password'
				end
			end
			
			devise_scope :user do
				post 'users/sign_up' => 'registrations#create'
				get 'reset_password' => 'passwords#new'
				get 'change_password' => 'passwords#edit'
				put 'update_user_password' => 'passwords#update'
			end

			scope :postulant do
				get 'team_match' => 'postulants#team_match'
			end

		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def results
    @postulants = Postulant.all.limit(5)
    @positions = ['Designer', 'Backend-Dev', 'Frontend-Dev', 'QA', 'Proyect Manager']
    @personality = ['Innovative', 'Adventurous', 'Logic Analyst', 'Innovative', 'Adventurous']

    render 'results'
  end

end

app/views/home/index.html.erb
<div class="grid">

  <div class="app-logo">
    <img src="<%= image_path 'app-logo.png' %>">
  </div>

  <h1>Build your dream Team</h1>

  <%= form_tag(results_path) do %>

      <div class="slider">

        <div class="inputs-container slide">

          <div class="input-block">
            <label>Company</label>
            <input name="company" placeholder="ex. Marvel">
          </div>


          <div class="input-block">
            <label>Project Name</label>
            <input name="project-name" placeholder="ex. LA, California (GMT-7)">
          </div>

          <div class="controls-container">
            <div class="next-question question-buttons">Next</div>
          </div>

        </div>


        <div class="inputs-container slide">

          <div class="input-block">
            <label>Time Zone Preferences</label>
            <input name="time-zone" placeholder="ex. + -2">
          </div>


          <div class="input-block">
            <label>Languaje</label>

            <div class="options-container gender-options">
              <input type="radio" id="java" name="gender" value="Java" checked/>
              <input type="radio" id="ruby" name="gender" value="Ruby"/>
              <input type="radio" id="python" name="gender" value="Python"/>
              <input type="radio" id="switf" name="gender" value="Swift"/>
            </div>

          </div>

          <div class="controls-container">
            <div class="prev-question question-buttons"><< Prev</div>
            <div class="next-question question-buttons">Next</div>
          </div>

        </div>

        <div class="inputs-container slide">

          <div class="input-block">
            <label>Kick Off</label>
            <input name="kick-off" type="date" placeholder="ex. 01/07/2019">
          </div>


          <div class="input-block">
            <label>Due Date</label>
            <input name="due-date" type="date" placeholder="ex. 09/12/2019">
          </div>

          <div class="controls-container">
            <div class="prev-question question-buttons"><< Prev</div>
            <input type="submit" class="next-question question-buttons" value="Create Team">
          </div>

        </div>

      </div>

  <% end %>
</div>

app/views/home/results.html.erb
<div class="grid">

  <div class="app-logo">
    <img src="<%= image_path 'app-logo.png' %>">
  </div>

  <h1>A team results</h1>

  <div class="team-container">
    <% if @postulants %>
        <% @postulants.each_with_index do |postulant, i| %>
            <div class="team-block">
              <%= image_tag postulant.avatar.url(:thumb) %>
              <div class="team-name"><%= postulant.name %></div>
              <div class="team-role"><%= @positions[i] %></div>
              <div class="team-skills">Commitment: <%= rand(1..5) %></div>
              <div class="team-skills">Social: <%= rand(1..5) %></div>
              <div class="team-skills">Productivity: <%= rand(1..5) %></div>
              <div class="team-skills">Personality: <%= @personality[i] %></div>
            </div>
        <% end %>
    <% end %>
  </div>


  <h3>Confirm team</h3>
  <div class="confirm-container">
    <a href="<%= root_path %>">yes</a>
    <a href="<%= root_path %>" class="redo">redo</a>
  </div>


</div>